### ISSUE TITLE
Transfer repository to pinobatch

### ISSUE THREAD

**Issue by pinobatch** [pinobatch/pently#16]
I think it's time to [transfer the repository](https://help.github.com/articles/about-repository-transfers/) to my account.

Background: I originally had Qix- post Pently to GitHub because I was unfamiliar with Git. (Before that, I was doing the "daily zipfile" method of naive version control.) I have since learned how to use Git.

Now: A member of the "FamiTracker Community" server on Discord wants me to [add a webhook](https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks) for Pently, so that whenever I commit something, the #development channel in that server gets notified. But only a repository's owner can add webhooks. I imagine that a lot more things I might do in the foreseeable future would require ownership as well.

**Comment by pinobatch** [comment]
The other option is for me to fork the repo, leaving this last version (right after the arpeggio upgrade) with you.

**Comment by Qix-** [comment]
No worries :) Check your inbox.

**Comment by pinobatch** [comment]
Accepted. Thanks.
