### ISSUE TITLE
Prevent make from running fceux

### ISSUE THREAD

**Issue by rogersachan** [pinobatch/pently#30]
I'm trying to run this script on a headless vm (WSL) and every time I run `make` it attempts to run fceux and causes an error code with make. Is there any way to opt out of launching fceux?

**Comment by pinobatch** [comment]
Use `make pently.nes` or `make pently.nsf` or `make all`. Or to make opting out the default, edit `makefile` and move the `map.txt $(title).nes` target and its recipe above the `run` target in the makefile.

Now let's turn this into a fixable issue. Where in the documentation would you have expected to find this information?

**Comment by rogersachan** [comment]
I would have expected to see this info in the README, in the section right below the level 3 header "Building". I would have expected it there since this section instructs the user to use make to operate the program.
