### ISSUE TITLE
Attack channel has a few bugs

### ISSUE THREAD

**Issue by retrodpc** [pinobatch/pently#35]
- Grace notes on attack channel are treated like regular notes
- Using dynamics on attack channel will cause it to break rehearsal points

[This file clearly demonstrates both bugs; please run it through the Pently compiler](https://github.com/pinobatch/pently/files/2716921/bugreport.txt)

**Comment by pinobatch** [comment]
In your example:

    time 4/4
    scale 16
    tempo 150

This sets 6 frames per row.

    e'8 f+' g' c#''8g d'' w2

The grace note duration is 8 frames, which exceeds one row.  From pentlyas.md:

> Be aware that grace notes longer than one row have poorly specified effects

However, a more well-formed pattern still displays a problem:

    e'8 f+' g' c#''16 w2g d'' w2
