### ISSUE TITLE
Port to ASM6

### ISSUE THREAD

**Issue by pinobatch** [pinobatch/pently#9]
Pently is made for ca65. But loopy wrote in the README file for his [ASM6](http://3dscapture.com/NES/) assembler that ca65 "took too much work to set up", and several users of [NESdev BBS](http://forums.nesdev.com/) agree.

In a forum post about [MML processors](http://forums.nesdev.com/viewtopic.php?p=178851#p178851), Pokun considers a requirement of ca65 to be a disadvantage for NSDL. In a forum post about music engines used by a ROM hacker turned original game programmer, dougeff expressed a bit of frustration about [upstream (us) being ahead of his port to ASM6](http://forums.nesdev.com/viewtopic.php?p=178156#p178156).

So consider ways to accommodate ASM6 users without having to [Write Everything Twice (WET)](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). This may involve a preprocessor of some sort to turn ca65 assembly source code to something ASM6 accepts. (I wrote a similar preprocessor for NESASM years ago as part of Action 53.) Steps I know I'll need to take:
- Assembler directives need not have a leading dot.
- `equ` replaces `=`; `=` instead replaces `.set`
- `db` or `byte` replaces `.byt`
- `dw` or `word` replaces `.addr`
- `dsb` replaces `.res`
- `rept` (with no second argument) replaces `.repeat`; emulate the second argument with `=`.
- `rept 1` replaces `.scope`
- No `.bss`; emulate it with `.enum` and `= $`. May need host to allocate both zero page and BSS memory.
- No other `.segment`; treat code and read-only data the same.
- No `.proc`; emulate it by either prefixing the namespace to non-`@` labels or perhaps wrapping the body in a `.rept 1`.
- No `.assert`; emulate it with `if`.
- No second argument to `.assert` either, but it can be emulated with `if`.
- Unnamed labels follow the x816 convention (`-`, `--`, `+foo`), not the ca65 convention (`:`). Change them to `@`-labels in the source code.

**Comment by Qix-** [comment]
I like ASM6 already. Do we know the percentage of users currently using ASM6 vs. CA65?

**Comment by pinobatch** [comment]
100 percent of NESmaker users are using ASM6

**Comment by pinobatch** [comment]
I may not want to bother make the tool translate the scope resolution operator, which allows referring to labels inside a different `.proc`. If we use `rept 1` for `.scope`, we can't do this. Fortunately, most of the over 80 uses of scope resolution are `.if ::` to force use of the top-level scope as a workaround for [cc65 issue #796](https://github.com/cc65/cc65/issues/796). For the others, break out a separate `.proc` with a fallthrough.

* `pently_resume_music::have_music_playing` becomes `pently_set_music_playing`
* `skip_to_row_top::bottom` becomes `pently_skip_to_row`
* `pently_play_note::skipAttackPart` becomes `pently_play_note_rts`
* `sustain_phase::silenced` becomes `silence_out_volume`

**Comment by pinobatch** [comment]
As of March 2019, Pokun still [rejects NSDL because of ca65](https://forums.nesdev.com/viewtopic.php?p=235648#p235648).

**Comment by pinobatch** [comment]
And right now I'm stuck on what to use to replace `.ifblank` and `.ifnblank` in a couple macros in pentlyseq.inc

**Comment by pinobatch** [comment]
Right now I'm stuck on trying to get pentlyseq.inc macros like `sfxdef` to work in ASM6. Here's an MCVE for what I'm seeing, heavily reduced from the definition of `sfxdef`:
```
; include guard mcve
; changing dw addy to dw 0 causes no error
; removing the ifndef/endif causes no error
ifndef INCLUDE_GUARD
INCLUDE_GUARD = 1
macro hello addy
dw addy
endm
endif
base $C000
hi:
hello data1
hello data2
data1:
data2:
```

**Comment by pinobatch** [comment]
Good news: 63ff9ae got all 10 sample songs playing. The next steps I can see:

- [ ] Preprocess the code and data separately, possibly involving changes to `pentlyas.py`
- [ ] Ask how ASM6 users expect libraries to allocate RAM
- [ ] Ask what sort of build system ASM6 users use
- [ ] Package the preprocessed code

**Comment by pinobatch** [comment]
Answers to some questions have arrived:

- Members of the NESdev Discord server recommended following the example of GGSound, which is shipped as three files: a first to include in zero page, a second one to include in BSS, and a third to include in code. The zero page and BSS files are supposed to `dsb` all bytes used in the library. `pentlybss.py` could be given this responsibility.
- [Discussion in NESdev BBS](https://forums.nesdev.com/viewtopic.php?f=2&t=18663) showed that ASM6 users expect to break large build processes that involve time-consuming asset conversion into two build processes, one run after the other. The first converts assets; the second assembles code. The process to build Pently would run during the second.
